# The first bit of code below is the MNIST example from the TensorFlow tutorial.

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

import tensorflow as tf
import time

def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)

def conv2d(x, W):
  return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
  return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1], padding='SAME')

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1,28,28,1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weight_variable([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = tf.matmul(h_fc1_drop, W_fc2) + b_fc2

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y_conv, y_))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(tf.initialize_all_variables())
start = time.time()
for i in range(20000):
  batch = mnist.train.next_batch(50)
  if i%100 == 0:
    train_accuracy = accuracy.eval(feed_dict={
        x:batch[0], y_: batch[1], keep_prob: 1.0})
    print("\rstep %d, training accuracy %g"%(i, train_accuracy), end="" if i%1000 else "\n")
  train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

elapsed = time.time()-start
print("\nTraining took {}".format(elapsed))
print("test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
step 0, training accuracy 0.1
step 400, training accuracy 0.96

KeyboardInterrupt: 

# Now this bit is the same thing adapted for use with an RBF based output layer.

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

import tensorflow as tf
import time

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                          strides=[1, 2, 2, 1], padding='SAME')

def RBFEuclidean(x, C):
    """Computes distance from cluster centers defined in input C
    
    Both outdim and indim should be integers.
    """
    return -tf.sqrt(tf.reduce_sum(tf.square(tf.sub(tf.expand_dims(x,2),
                                                   tf.expand_dims(C,0))),1))

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1,28,28,1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weight_variable([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = RBFEuclidean(h_fc1_drop, W_fc2) + b_fc2

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y_conv, y_))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(tf.initialize_all_variables())
start = time.time()
for i in range(20000):
  batch = mnist.train.next_batch(50)
  if i%100 == 0:
    train_accuracy = accuracy.eval(feed_dict={
        x:batch[0], y_: batch[1], keep_prob: 1.0})
    print("\rstep %d, training accuracy %g"%(i, train_accuracy), end="" if i%1000 else "\n")
  train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

elapsed = time.time()-start
print("\nTraining took {}".format(elapsed))
print("\ntest accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
step 0, training accuracy 0.14
step 1000, training accuracy 0.96
step 2000, training accuracy 0.96
step 3000, training accuracy 1
step 4000, training accuracy 0.98
step 5000, training accuracy 1
step 6000, training accuracy 1
step 7000, training accuracy 0.98
step 8000, training accuracy 1
step 9000, training accuracy 0.96
step 10000, training accuracy 0.98
step 11000, training accuracy 0.98
step 12000, training accuracy 1
step 13000, training accuracy 1
step 14000, training accuracy 0.98
step 15000, training accuracy 1
step 16000, training accuracy 1
step 17000, training accuracy 0.98
step 18000, training accuracy 1
step 19000, training accuracy 1
step 19900, training accuracy 1
Training took 87.44569039344788

test accuracy 0.9928


# Now with the custom implementation

In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

import tensorflow as tf
euclidean_dist_module = tf.load_op_library("euclidean_dist.so")
euclidean_dist = euclidean_dist_module.euclidean_dist
euclidean_dist_grad = euclidean_dist_module.euclidean_dist_grad

from tensorflow.python.framework import ops
@ops.RegisterGradient("EuclideanDist")
def _EuclideanDistGrad(op, grad):
    a = op.inputs[0]
    b = op.inputs[1]
    y = op.outputs[0]  # y = 0.5 * b / conj(a)
    #TODO: eventually replace with this
    #gradient_over_distance = tf.select(tf.not_equal(y,0),grad/y,y)
    #xGrad, cGrad = euclidean_dist_grad(a,b,gradient_over_distance)
    xGrad, cGrad = euclidean_dist_grad(a,b,y,grad)
    return xGrad, cGrad

import time


def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                          strides=[1, 2, 2, 1], padding='SAME')

def RBFEuclidean(x, C):
    """Computes distance from cluster centers defined in input C
    
    Both outdim and indim should be integers.
    """
    return -euclidean_dist(x,C)

#""" #Uncomment these quotes to use GPU
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
#""" #Uncomment these quotes to use GPU
sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1,28,28,1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weight_variable([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = RBFEuclidean(h_fc1_drop, W_fc2) + b_fc2

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y_conv, y_))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
sess.run(tf.initialize_all_variables())
start = time.time()
for i in range(20000):
  batch = mnist.train.next_batch(50)
  if i%100 == 0:
    train_accuracy = accuracy.eval(feed_dict={
        x:batch[0], y_: batch[1], keep_prob: 1.0})
    print("\rstep %d, training accuracy %g"%(i, train_accuracy), end="" if i%1000 else "\n")
  train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})

elapsed = time.time()-start
print("\nTraining took {}".format(elapsed))
print("\ntest accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


NotFoundError: No session factory registered for the given session options: {target: "cpu:0" config: graph_options { place_pruned_graph: true }} Registered factories are {GRPC_SESSION, DIRECT_SESSION}.

In [3]:
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [4]:
euclidean_dist(a,b).eval()

array([[ 1.38092985,  1.15982624,  2.57892774],
       [ 2.73553414,  1.99491866,  1.82233465],
       [ 1.75136915,  1.24030816,  3.00059217]])

In [5]:
RBFEuclidean(a,b).eval()

array([[-1.38092985, -1.15982624, -2.57892774],
       [-2.73553414, -1.99491866, -1.82233465],
       [-1.75136915, -1.24030816, -3.00059217]])

In [6]:
(euclidean_dist(a,b)+RBFEuclidean(a,b)).eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [ ]:
#Okay. Forward propagation is roughly exactly correct. So I screwed up backprop... Go figure.

In [3]:
x = tf.placeholder("float", [1,1])
y = tf.placeholder("float", [1,1])
c = weight_variable([1,1])
cpu = euclidean_dist(x,c)
proto = RBFEuclidean(x,c)
xdata = [[1]]
cinitial = [[-1]]
c.assign(cinitial).eval()
yexpected = [[0]]# euclidean_dist(x,x).eval({x:xdata})
#yexpected[1,1] = 1
gradCPU = tf.gradients(tf.reduce_sum(tf.abs(cpu-yexpected)),c) #absolute error loss
gradProto = tf.gradients(tf.reduce_sum(tf.abs(proto+yexpected)),c)

In [4]:
tf.get_default_session().run(gradCPU, feed_dict={x:xdata, y:yexpected})

[array([[-1.]], dtype=float32)]

In [5]:
tf.get_default_session().run(gradProto, feed_dict={x:xdata, y:yexpected})

[array([[-1.]], dtype=float32)]

In [6]:
yexpected

[[0]]

In [7]:
cpu.eval({x:xdata})

array([[ 2.]], dtype=float32)

In [8]:
proto.eval({x:xdata})

array([[-2.]], dtype=float32)

In [9]:
c.assign(np.array(cinitial) - tf.get_default_session().run(gradProto, feed_dict={x:xdata, y:yexpected})[0]).eval()

array([[ 0.]], dtype=float32)

In [10]:
tf.get_default_session().run(gradCPU, feed_dict={x:xdata, y:yexpected})

[array([[-1.]], dtype=float32)]

In [11]:
cpu.eval({x:xdata})

array([[ 1.]], dtype=float32)

In [ ]:
# EVERYTHING IS WORKING NOW! And it should be more numerically stable than
#  the prototype version, but it's rare for x==c so that point may not be
#  important.

In [7]:
# Turns out there was a gradient_checker all along. The documentation points to the wrong place.
# They need to update it to point to the code for
from tensorflow.python.ops.gradient_checker import compute_gradient

In [54]:
a = tf.Variable([[0.,1.],[1.,0.]])
b = tf.Variable([[3.,0.],[2.,0.]])
tf.get_default_session().run(tf.initialize_variables([a,b]))

tf.select(tf.not_equal(b,0),a/b,b).eval()

array([[ 0. ,  0. ],
       [ 0.5,  0. ]], dtype=float32)